# Disable the newline at the start of the prompt
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Wait 0 milliseconds for starship to check files under the current directory
scan_timeout = 0

# PHP
[php]
format = "[ğŸ˜ $version](147 bold) "
